import json

notebook_path = "ai_vs_real_classification.ipynb"
with open(notebook_path, 'r') as f:
    nb = json.load(f)

# Update class_weights_tensor logic in Section 5
for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        source = cell['source']
        for i, line in enumerate(source):
            if "class_weights_tensor = (weights / weights.sum()).to(device)" in line:
                source.insert(i, "weights[1] = weights[1] * 5.0 # Penalize False Positives for AI-Generated by giving Real class 5x weight\n")
                break

# Add LIME cell
lime_markdown = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Section 10 — LIME Interpretability\n",
        "**What this does:** Uses Local Interpretable Model-Agnostic Explanations to generate superpixel boundaries showing which parts of an image contributed to the model's decision."
    ]
}

lime_code = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import lime\n",
        "from lime import lime_image\n",
        "from skimage.segmentation import mark_boundaries\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn.functional as F\n",
        "from torchvision import transforms\n",
        "\n",
        "explainer = lime_image.LimeImageExplainer()\n",
        "\n",
        "def predict_fn_lime(images):\n",
        "    model_0.eval()\n",
        "    device = next(model_0.parameters()).device\n",
        "    \n",
        "    batch = torch.tensor(images, dtype=torch.float32).permute(0, 3, 1, 2)\n",
        "    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
        "    batch = torch.stack([normalize(img) for img in batch]).to(device)\n",
        "    \n",
        "    with torch.inference_mode():\n",
        "        logits = model_0(batch)\n",
        "        probs = F.softmax(logits, dim=1)\n",
        "        \n",
        "    return probs.cpu().numpy()\n",
        "\n",
        "model_0.eval()\n",
        "sample_img_tensor, sample_label = next(iter(test_dl_0))\n",
        "sample_img_tensor = sample_img_tensor[0]\n",
        "sample_label = sample_label[0].item()\n",
        "\n",
        "inv_normalize = transforms.Normalize(\n",
        "    mean=[-0.485/0.229, -0.456/0.224, -0.406/0.225],\n",
        "    std=[1/0.229, 1/0.224, 1/0.225]\n",
        ")\n",
        "img_for_lime = inv_normalize(sample_img_tensor).permute(1, 2, 0).cpu().numpy()\n",
        "img_for_lime = np.clip(img_for_lime, 0, 1)\n",
        "\n",
        "print(f\"Generating LIME explanation for Class: {class_names[sample_label]}...\")\n",
        "explanation = explainer.explain_instance(\n",
        "    img_for_lime, \n",
        "    predict_fn_lime, \n",
        "    top_labels=2, \n",
        "    hide_color=0, \n",
        "    num_samples=1000\n",
        ")\n",
        "\n",
        "temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=False, num_features=10, hide_rest=False)\n",
        "plt.figure(figsize=(6,6))\n",
        "plt.imshow(mark_boundaries(temp, mask))\n",
        "plt.title(f\"LIME - Pred: {class_names[explanation.top_labels[0]]} | Actual: {class_names[sample_label]}\")\n",
        "plt.axis('off')\n",
        "plt.show()\n"
    ]
}

# Add SHAP cell
shap_markdown = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Section 11 — SHAP Interpretability\n",
        "**What this does:** Uses SHapley Additive exPlanations (GradientExplainer) to produce pixel-level attribution maps."
    ]
}

shap_code = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import shap\n",
        "import numpy as np\n",
        "\n",
        "batch = next(iter(test_dl_0))\n",
        "images, labels = batch\n",
        "images = images.to(device)\n",
        "\n",
        "print(\"Generating SHAP explanations...\")\n",
        "background = images[:16]\n",
        "test_images = images[16:18] # Take 2 images for SHAP to avoid out-of-memory\n",
        "\n",
        "explainer_shap = shap.GradientExplainer(model_0, background)\n",
        "shap_values = explainer_shap.shap_values(test_images)\n",
        "\n",
        "if isinstance(shap_values, list):\n",
        "    shap_numpy = [np.swapaxes(np.swapaxes(s, 1, -1), 1, 2) for s in shap_values]\n",
        "else:\n",
        "    shap_numpy = np.swapaxes(np.swapaxes(shap_values, 1, -1), 1, 2)\n",
        "\n",
        "test_numpy = np.swapaxes(np.swapaxes(test_images.cpu().numpy(), 1, -1), 1, 2)\n",
        "\n",
        "mean = np.array([0.485, 0.456, 0.406])\n",
        "std = np.array([0.229, 0.224, 0.225])\n",
        "test_numpy = std * test_numpy + mean\n",
        "test_numpy = np.clip(test_numpy, 0, 1)\n",
        "\n",
        "shap.image_plot(shap_numpy, test_numpy)\n"
    ]
}

nb['cells'].extend([lime_markdown, lime_code, shap_markdown, shap_code])

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)

print("Notebook successfully updated.")
